# Generated by Django 4.2.20 on 2025-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dispute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputecase',
            name='disputed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
