# Generated by Django 4.2.20 on 2025-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_dispute', '0002_disputecase_disputed_amount_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputecase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
